hex:  ${PATTERN:=.hex}

$(info $$TESTNAME is [${TESTNAME}])

# ../../gpio_config/gpio_config_data.c: ../../gpio_config/gpio_config_def.py
# 	cd ../../gpio_config; python3 ../../gpio_config/gpio_config_builder.py

$(TESTNAME).elf: $(TESTNAME).c ../../sections.lds ../../crt0_vex.S 
	$(TOOLCHAIN_PATH)riscv64-unknown-elf-gcc -I../../ -I../../generated/ -I../common/ -O0 -mabi=ilp32 -march=rv32i -D__vexriscv__ -Wl,-Bstatic,-T,../../sections.lds,--strip-debug -ffreestanding -nostdlib -o $@ ../../crt0_vex.S ../../isr.c ../../gpio_program.c $<

	${TOOLCHAIN_PATH}riscv64-unknown-elf-objdump -s  cpu_stress.elf > cpu_stress.lst

$(TESTNAME).hex: $(TESTNAME).elf
	$(TOOLCHAIN_PATH)riscv64-unknown-elf-objcopy -O verilog $< $@
	sed -ie 's/@10/@00/g' $@
	
%.bin: %.elf
	$(TOOLCHAIN_PATH)$(TOOLCHAIN_PREFIX)-unknown-elf-objcopy -O binary $< $@

client: client.c
	gcc client.c -o client

flash: cpu_stress.hex
	python3 ../util/caravel_hkflash.py cpu_stress.hex
	python3 ../util/caravel_hkstop.py

flash2: cpu_stress.hex
	python3 ../util/caravel_flash.py cpu_stress.hex

# ---- Clean ----

clean:
	rm -f *.elf *.hex *.bin *.vvp *.vcd *.hexe *.lst *.hexe *.lst

.PHONY: clean hex all flash